// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return $(".jumbotron").jumbotron({
      slideshow: false,
      slideshowInterval: 2500,
      switcher: true,
      switcherSelector: '.switcher'
    });
  });

}).call(this);
